name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Docusaurus Site
        run: bun run build

      - name: Copy CNAME # to ensure redirection keeps working
        run: cp ./CNAME ./build/
      
      # setup github user and email to github bot
      - uses: qoomon/actions--setup-git@v1
        with:
            user: bot

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build